// <auto-generated />
using System;
using InterviewSimulator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InterviewSimulator.Migrations
{
    [DbContext(typeof(MockMateDbContext))]
    [Migration("20260210162510_AddCvAnalysisJson")]
    partial class AddCvAnalysisJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InterviewSimulator.Models.CareerTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ResourceLink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__CareerTa__3214EC0754A191E6");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("CareerTasks");
                });

            modelBuilder.Entity("InterviewSimulator.Models.InterviewSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<byte?>("CareerFitRating")
                        .HasColumnType("smallint");

                    b.Property<string>("CvAnalysisJson")
                        .HasColumnType("text");

                    b.Property<byte>("DifficultyLevel")
                        .HasColumnType("smallint");

                    b.Property<byte>("DurationMode")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("JobPositionId")
                        .HasColumnType("integer");

                    b.Property<string>("OverallFeedback")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<byte?>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((byte)0);

                    b.Property<double?>("TotalScore")
                        .HasColumnType("double precision");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__Intervie__3214EC07FDB0FBC0");

                    b.HasIndex("JobPositionId");

                    b.HasIndex(new[] { "UserId" }, "IX_Sessions_UserId");

                    b.ToTable("InterviewSessions");
                });

            modelBuilder.Entity("InterviewSimulator.Models.JobCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("PK__JobCateg__3214EC075CD0F836");

                    b.ToTable("JobCategories");
                });

            modelBuilder.Entity("InterviewSimulator.Models.JobPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id")
                        .HasName("PK__JobPosit__3214EC07251D81B3");

                    b.HasIndex("CategoryId");

                    b.ToTable("JobPositions");
                });

            modelBuilder.Entity("InterviewSimulator.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<byte>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("TransactionCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("TransactionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("InterviewSimulator.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC079D16F90C");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160419B7CE0")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("InterviewSimulator.Models.SessionDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiFeedback")
                        .HasColumnType("text");

                    b.Property<string>("AnswerAudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AnswerContent")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Score")
                        .HasColumnType("double precision");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int?>("TimeTakenSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK__SessionD__3214EC07F2C70D0B");

                    b.HasIndex(new[] { "SessionId" }, "IX_Details_SessionId");

                    b.ToTable("SessionDetails");
                });

            modelBuilder.Entity("InterviewSimulator.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CvExtractedText")
                        .HasColumnType("text");

                    b.Property<string>("CvUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ExperienceYears")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsVip")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(2);

                    b.Property<DateTime?>("VipExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK__Users__3214EC071C109775");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "IX_Users_Email");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534420FDE55")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("InterviewSimulator.Models.CareerTask", b =>
                {
                    b.HasOne("InterviewSimulator.Models.InterviewSession", "Session")
                        .WithMany("CareerTasks")
                        .HasForeignKey("SessionId")
                        .HasConstraintName("FK_Tasks_Sessions");

                    b.HasOne("InterviewSimulator.Models.User", "User")
                        .WithMany("CareerTasks")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Tasks_Users");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InterviewSimulator.Models.InterviewSession", b =>
                {
                    b.HasOne("InterviewSimulator.Models.JobPosition", "JobPosition")
                        .WithMany("InterviewSessions")
                        .HasForeignKey("JobPositionId")
                        .IsRequired()
                        .HasConstraintName("FK_Sessions_Jobs");

                    b.HasOne("InterviewSimulator.Models.User", "User")
                        .WithMany("InterviewSessions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Sessions_Users");

                    b.Navigation("JobPosition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InterviewSimulator.Models.JobPosition", b =>
                {
                    b.HasOne("InterviewSimulator.Models.JobCategory", "Category")
                        .WithMany("JobPositions")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_JobPositions_Categories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("InterviewSimulator.Models.PaymentTransaction", b =>
                {
                    b.HasOne("InterviewSimulator.Models.User", "User")
                        .WithMany("PaymentTransactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Users");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InterviewSimulator.Models.SessionDetail", b =>
                {
                    b.HasOne("InterviewSimulator.Models.InterviewSession", "Session")
                        .WithMany("SessionDetails")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Details_Sessions");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("InterviewSimulator.Models.User", b =>
                {
                    b.HasOne("InterviewSimulator.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_Users_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("InterviewSimulator.Models.InterviewSession", b =>
                {
                    b.Navigation("CareerTasks");

                    b.Navigation("SessionDetails");
                });

            modelBuilder.Entity("InterviewSimulator.Models.JobCategory", b =>
                {
                    b.Navigation("JobPositions");
                });

            modelBuilder.Entity("InterviewSimulator.Models.JobPosition", b =>
                {
                    b.Navigation("InterviewSessions");
                });

            modelBuilder.Entity("InterviewSimulator.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("InterviewSimulator.Models.User", b =>
                {
                    b.Navigation("CareerTasks");

                    b.Navigation("InterviewSessions");

                    b.Navigation("PaymentTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
